name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: downcase REPO #Repository name might contain uppercase letters that do not work with the docker registry
      run: |
        echo "repo=${github.repository,,}" >> "${GITHUB_ENV}"
    
    - name: Generate Timestamp
      run: |
        echo "timestamp=$(date +%s)" >> "${GITHUB_ENV}"
        
    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/$repo/my-image-name:$timestamp

    # Step 4: Push the Docker image to GHCR
    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/$repo/my-image-name:$timestamp
